### ISSUE TITLE
syslog-ng.conf from repo is not added to the image

### ISSUE THREAD

**Issue by abalage** [balabit/syslog-ng-docker#17]
The documentation suggests to expose ports in order to be able to receive messages from network, however the image does not contain the necessary .conf file from the git repository but it contains the factory conf shipped by the .deb file.

ps. also the default config file has @version: 3.6 which is outdated taking into account that the image has version 3.7.2.

**Comment by markvr** [comment]
This image is completely broken, as it doesn't appear to do anything even if you do add it this configuration file.  The configuration I used is:

```
@version:3.9

@include "scl.conf"


options {
    flush_lines (0);
    time_reopen (10);
    log_fifo_size (1000);
    chain_hostnames (off);
    use_dns (no);
    use_fqdn (no);
    create_dirs (yes);
    keep_hostname (yes);
};

source s_sys {
    system();
    internal();
    udp(ip(0.0.0.0) port(514));
    tcp(ip(0.0.0.0) port(514));
};

destination d_mesg { file("/var/log/messages"); };

log { source(s_sys); destination(d_mesg); };

```

With an entry point of:
`ENTRYPOINT ["/usr/sbin/syslog-ng", "-e", "-F", "-f", "/syslog-ng.conf", "--no-caps"]`

**Comment by mitzkia** [comment]
Hi, 

Sorry, could you explain why the image is "completely broken"? You can always use the image with your custom configuration file, syslog-ng will work with it. For example (of course with defined specific ports if needed):
`docker run -it -v "$PWD/syslog-ng.conf":/etc/syslog-ng/syslog-ng.conf balabit/syslog-ng:latest -edvt --no-caps`

That is true the currently added syslog-ng.conf is outdated. We can update it with default config file:
https://github.com/balabit/syslog-ng/blob/master/scl/syslog-ng.conf

**Comment by markvr** [comment]
Sorry "completely broken" was probably a bit strong but I was getting pretty frustrated!   
Firstly the default image fails with error: `syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted`,  so I googled and found you need to start with the `--no-caps` options.

Then the docs say "You can check the default configuration in the source repository of this image." but that file isn't actually added to the repo, so I don't know what the default configuration is.  I then added it manually (as per the instructions), but it failed with an error about mismatched configuration version (3.7 vs 3.9).  I updated the file to 3.9 but that still doesn't listen on the TCP/UDP ports in the docs.  

In the end, I wrote my own config file (above), copied it to the root of the image, updated the ENTRYPOINT to specify `--no-caps` and that finally seems to work.

**Comment by MrAnno** [comment]
We've moved the syslog-ng Docker image to our main repository, where the default configuration is up-to-date and it is, of course, added to the image.
