### ISSUE TITLE
Port 514 with UDP doesn't work

### ISSUE THREAD

**Issue by gyszalai** [balabit/syslog-ng-docker#19]
It seems that port 514 is exposed with TCP instead of UDP, so connecting to the 
syslog-ng server with UDP is not working. 

The solution might be this:

```
EXPOSE 601/tcp 514/udp ...
```

**Comment by mitzkia** [comment]
Hi, 
Sorry for the late answer. 
Of course the issue is valid. It has been fixed.

Andras

**Comment by Mausy5043** [comment]
The start command in the README should also be changed:

Something like this perhaps?
```
docker run -d -p 514:514/udp -p 601:601 --name syslog-ng balabit/syslog-ng:latest
```
