### ISSUE TITLE
Problem Starting syslog-ng-docker with Ubuntu 16.10

### ISSUE THREAD

**Issue by DaGeRe** [balabit/syslog-ng-docker#21]
Hi,

I've tried to start syslog-ng just like described on the page https://hub.docker.com/r/balabit/syslog-ng/, but unfortunately this leads to only the output:

> syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'

According to http://serverfault.com/questions/524518/error-setting-capabilities-capability-management-disabled, this is a problem of kernel and syslog-ng versions. Mounting a syslog-ng file with -v syslog-ng:/etc/default/syslog-ng does not work, since this is not a directory. 

Is there any known workaround for this issue?

https://github.com/bobrik/docker-syslog-ng works fine.

Best regards,
DaGeRe

**Comment by mitzkia** [comment]
Hi, 

Thanks for trying syslog-ng-docker project.  
The answer for the first question is with the default starting method: `ENTRYPOINT ["/usr/sbin/syslog-ng", "-F"]` syslog-ng needs specific POSIX capabilty flags. But docker did not grants it by default. 
To grant it you have some docker options, for example:
1, grant only the specific capabilities:
`docker run --cap-add NET_BIND_SERVICE --cap-add NET_BROADCAST --cap-add NET_RAW --cap-add DAC_READ_SEARCH --cap-add DAC_OVERRIDE --cap-add CHOWN --cap-add SYSLOG -it -p 514:514 -p 601:601 --name syslog-ng balabit/syslog-ng:latest`
2, most of the capabilities:
`docker run --privileged  -it -p 514:514 -p 601:601 --name syslog-ng balabit/syslog-ng:latest`
3, you can run syslog-ng without any capabilities
`docker run -it -p 514:514 -p 601:601 --name syslog-ng balabit/syslog-ng:latest --no-caps`

To check syslog-ng correctly started you can run docker image in a following way:
`docker run -it -p 514:514 -p 601:601 --name syslog-ng balabit/syslog-ng:latest -edvt --no-caps`

The answer for your second question. You need to start docker in a following way to override the default configuration (-v [full path to the syslog-ng config on your host]:[/etc/syslog-ng/syslog-ng.conf]):
`docker run -it -v "$PWD/syslog-ng.conf":/etc/syslog-ng/syslog-ng.conf balabit/syslog-ng:latest`

Hope it helps
Andras

**Comment by chairbender** [comment]
I tried using your image and it wouldn't work. Got the error mentioned above, and logs were sent to the syslog service but were not written to /var/log/syslog. Was fixed by switching to bobrik/docker-syslog-ng.

**Comment by danydev** [comment]
Same problem here

**Comment by szemere** [comment]
Hello @danydev ,
 please give us some details about your configuration. The command you typed in, the ID of the image you started (,anything else you feel relevant to your problem).

 note: This is the first time I met with this problem. I can see some key differences between bobrik's container and this _example_ one. (Yes, it is intended to be customized like bobrik's did.)
For example, without
`-v /var/log/syslog-ng:/var/log/syslog-ng`
the logs are collected inside the containers file system, and not on the host machine.

Br,
Laci

**Comment by danydev** [comment]
Hello @szemere , 
thank you, I finally solved. For reference: in my `docker-compose.yml` file

```
  syslogng:
    image: balabit/syslog-ng:3.14.1
    hostname: syslogng
```

then `docker-compose up -d`, and then `docker logs syslogng` shows `syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'`. Solved by adding `command: "--no-caps"`

**Comment by szemere** [comment]
Hello @danydev ,
 I am very glad that it is working now. (It's good to hear you are using docker compose!)
 I am closing this ticket, since it looks like every mentioned case is about the lack of proper capabilities. Please feel free to open a new ticket in case of other error messages.

Br,
Laci

**Comment by charlesritchea** [comment]
@szemere Shouldn't you mention this on the dockerhub README? This happens with CentOS 7 as well. I would only know how to solve this by finding this closed ticket

**Comment by szemere** [comment]
Hello @novaterata,
 thank you for the comment and sorry for the late. (I forgot to push the commit.)

 please review #34

Br,
Laci

**Comment by Mausy5043** [comment]
Just a quick note, as I ran into the same problem and Googling it brought me here.  
The current version of `docker` does not support the `--no-caps` option. 
However what does seem to work for me is changing the `Dockerfile` to start the daemon thus:


```
ENTRYPOINT ["/usr/sbin/syslog-ng", "-F", "--no-caps"]
```

**Comment by Kokan** [comment]
The `--no-caps` is not a `docker` option, in docker cli everything after the image name is passed as argument to the `entrypoint` (`cmd` in docker terminology).

Which in case of this image in fact `syslog-ng` that has a `--no-caps` option.
