### ISSUE TITLE
Deprecation of balabit/syslog-ng-dev and balabit/syslog-ng-incubator-dev images

### ISSUE THREAD

**Issue by mitzkia** [balabit/syslog-ng-docker#24]
We want to deprecate outdated dev images:
   * balabit/syslog-ng-dev and 
   * balabit/syslog-ng-incubator-dev

New dev images will be available from here (they will be also auto builded):
 * https://hub.docker.com/r/balabit/syslog-ng-zesty/
 * https://hub.docker.com/r/balabit/syslog-ng-centos7/
 * https://hub.docker.com/r/balabit/syslog-ng-xenial/
 * https://hub.docker.com/r/balabit/syslog-ng-jessie/

Todo:
* add notification in readme about the deprecation
* delete the source directories 
* delete old dev images: balabit/syslog-ng-dev, balabit/syslog-ng-incubator-dev
* add reference for new dev images

**Comment by MrAnno** [comment]
Done. I think complete deletion is not needed anymore as we are planning to archive this repository.
