### ISSUE TITLE
setting the timezone of the environment inside the container

### ISSUE THREAD

**Issue by elrido** [balabit/syslog-ng-docker#33]
## Problem description

I am using the syslog-ng image to aggregate syslog on my environment and forward it all into Elasticsearch for consumption by Kibana (also running in containers).

This all works fine, except that all the timestamps have two hours deducted. After some investigation I found that the issue stems from the docker host and all environment systems running on CEST (UTC+2), but the syslog-ng container has default timezone settings of UTC, so syslog assumes all the logs it gets with CEST values have to be converted when passing them on to elastic.

## Workaround

I can docker exec into the running syslog container and run `dpkg-reconfigure tzdata` to set the container to CEST, too. Without restarting the syslog process, the timestamps immediately start to arrive correctly in Elastic.

This is no real solution as I would have to re-do this step when restarting the syslog container. Fortunately syslog runs really stable and did not crash or otherwise needed to be restarted. But any kernel upgrade of the Docker host would cause a restart and would require reapplication of this change.

## Possible solutions

- I could bake my own syslog image with just the timezone adjusted.
- An environment variable could be offered to allow to specify the system timezone used in the image
- Some other means of configuration could be added to the image to set the system timezone

If any of the latter two would be preferred, would you accept a pull request to add such an option to the image, and if so, what would your preferred way of configuring this be?

## Environment

Docker host: Ubuntu 16.04 LTS / Docker 1.13.1 / Linux 4.4.0
Docker image: balabit/syslog-ng:3.14.1
Syslog-NG configuration:
```
@version: 3.14
@module mod-java
@include "scl.conf"

options {
    keep-hostname(no);
    chain-hostnames(no);
};

source s_network {
    network(
        transport("udp")
    );
};

destination d_elastic {
    elasticsearch2(
        client-mode("http")
        cluster("log")
        index("syslog-${YEAR}-${MONTH}-${DAY}")
        cluster-url("http://localhost:9200")
        type("slng_test_type")
        flush-limit("0")
        time-zone("UTC")
    );
};

log {
   source(s_network);
   destination(d_elastic);
   flags(flow-control);
};
```

**Comment by mitzkia** [comment]
Hi @elrido 

Thanks for your detection. 
Did you mean such thing in the second solution (when using env. variable)?
```
$ docker run -e TZ=Europe/Budapest ... 
```
And in this case if `tzdata` package already installed it should be work. 

Of course Pull Request always welcome :)

**Comment by mitzkia** [comment]
When I wrote my previous comment I could not check the image itself. If there is a `tzdata` package or not. But now I have checked and it is already installed. 
So if I am right the above solution should work. 

From my side (let set timezone to BST):
```
$ docker run -it -e TZ=Europe/London balabit/syslog-ng -edv
$ docker exec -it c5582fb87c77 date
Mon Jul 23 08:04:14 BST 2018
```

or, let set timezone to EDT:
```
docker run -it -e TZ=America/New_York balabit/syslog-ng -edv
docker exec -it 76ddd75458c3 date
Mon Jul 23 03:05:32 EDT 2018
```

Is it ok for you? Or did you mean something else?

**Comment by elrido** [comment]
Thank you for getting back on this so quickly. I will test it on my environment and update this thread with my findings.

As my original workaround is proof of, tzdata is indeed installed. I didn't realize that this lets us control the container by just setting the TZ environment, so likely there will not be any change necessary. I'll confirm later today, after some testing.

**Comment by elrido** [comment]
I can confirm 100% that setting the `TZ` environment variable solves my issue permanently and reliably. No need to change anything in the image. Thank you very much!
