### ISSUE TITLE
Provide version tags on hub.docker.com

### ISSUE THREAD

**Issue by jmervine** [balabit/syslog-ng-docker#38]
Please provide version tags on hub.docker.com for better version locking in production use.

I notice this issue was raised before in https://github.com/balabit/syslog-ng-docker/issues/29 but the tags show the last version tag to be several version and months out of date.

```
$ docker run --entrypoint= balabit/syslog-ng:latest syslog-ng --version
syslog-ng 3 (3.18.1)
Config version: 3.18
Installer-Version: 3.18.1
Revision: 3.18.1-1
Compile-Date: Oct 24 2018 10:04:41
Module-Directory: /usr/lib/syslog-ng/3.18
Module-Path: /usr/lib/syslog-ng/3.18
Available-Modules: linux-kmsg-format,json-plugin,kvformat,afsocket,afmongodb,disk-buffer,http,basicfuncs,pacctformat,examples,afamqp,geoip2-plugin,xml,mod-python,map-value-pairs,tags-parser,date,redis,geoip-plugin,csvparser,system-source,syslogformat,confgen,afsmtp,tfgetent,afstomp,affile,cryptofuncs,add-contextual-data,appmodel,hook-commands,riemann,snmptrapd-parser,afprog,stardate,mod-java,afuser,graphite,dbparser,pseudofile,afsql,cef,sdjournal
Enable-Debug: off
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: on
Enable-TCP-Wrapper: on
Enable-Linux-Caps: on
Enable-Systemd: on
```

**Comment by szemere** [comment]
Hello,
 this is an old dept from us. Unfortunately there are some manual steps between the GitHub release (which is automated) and the Docker image build (which is also automated).

 I tagged the `latest` image now with the 3.19.1 version, and added this step to our internal release guide, but currently I can not ensure this will happen in the future. (In an automated way.) I will do my best.

Br,
Laci

**Comment by ryanfaircloth** [comment]
would it be possible to merge the dockerbuild into the main repo. Could we not have travis build docker "latest" and version tags when a release is cut?

**Comment by furiel** [comment]
@rfaircloth-splunk I am afraid the situation is a little more complex than that. The main repository is responsible for providing a release tarball. But syslog-ng in the images are not built from source, but installed as debian packages from the unofficial repository hosted at build.opensuse.org (OBS). So the trigger point is when the packages are generated in OBS. What would resolve this if the packages in OBS could be generated automatically, and OBS could trigger the docker image generation once the packages are available. But OBS is a very complex topic on its own. So for now we are doing all these steps manually.

**Comment by drexlma** [comment]
https://hub.docker.com/r/balabit/syslog-ng/tags

resolved & close?

**Comment by MrAnno** [comment]
Tags are still pushed manually, I think we should keep this issue open until we find a way to automate this with OBS, or just document as a step in the release process.

**Comment by szemere** [comment]
Updated: https://github.com/syslog-ng/syslog-ng/releases/tag/syslog-ng-3.30.1
