### ISSUE TITLE
port 6514/tcp

### ISSUE THREAD

**Issue by Mausy5043** [balabit/syslog-ng-docker#39]
Why is port 6514 exposed in `Dockerfile`? 

It doesn't seem to get used when following the README.
Can I just add a `-p 6514:6514` to the start command?

**Comment by bazsi** [comment]
If you look at the default config in the dockerfile, it uses
default-network-drivers(), which does open port 6514, for tls encapsulated
rfc5424 style messages.

If you override the config, yours may or may not do the same.

Bazsi

**Comment by drexlma** [comment]
close?

https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/release-notes/default-network-drivers-receive-and-parse-common-syslog-messages

**Comment by MrAnno** [comment]
@drexlma Thanks.

The question has been answered, closing.
