### ISSUE TITLE
add HEALTHCHECK

### ISSUE THREAD

**Issue by drexlma** [balabit/syslog-ng-docker#43]
Like

HEALTHCHECK  --interval=2m --timeout=3s --start-period=30s CMD /etc/init.d/nginx status  || exit 1

**Comment by mitzkia** [comment]
Hi @drexlma 

Thank you for using syslog-ng-docker. 
As soon as I can I will check the usage of HEALTHCHECK, and if it is fine I will add this functionality. 
But if you would like you can also put it in a PR. :)

Thanks

**Comment by drexlma** [comment]
https://github.com/balabit/syslog-ng-docker/pull/45
