### ISSUE TITLE
Doesnt start

### ISSUE THREAD

**Issue by CurlyFlow** [balabit/syslog-ng-docker#48]
So im on unraid, pulled your container, didnt found any additional steps to do (besides go to :8000, which dont work, because the container wont even start)

*** Running /etc/rc.local...
ERROR: Couldn't read "/opt/splunk/etc/splunk-launch.conf" -- maybe $SPLUNK_HOME or $SPLUNK_ETC is set wrong?

*** Booting runit daemon...
*** Runit started as PID 8
Nov 15 08:26:58 98d43466988b syslog-ng[14]: syslog-ng starting up; version='3.5.3'

I tried putting a conf there, but i dont know the correct variables so i get some varios other errors when i put some conf file there.

Maybe you can provide the correct conf file so i can copy it to the correct directory?

**Comment by CurlyFlow** [comment]
I tried now this: https://github.com/balabit/syslog-ng-docker/blob/master/syslog-ng/syslog-ng.conf

It starts correct now: 

*** Running /etc/rc.local...
Could not open version file "/opt/splunk/etc/splunk.version" (2).


This appears to be your first time running this version of Splunk.

*** Booting runit daemon...
*** Runit started as PID 8
Nov 15 08:35:54 a688b24c81ac syslog-ng[13]: syslog-ng starting up; version='3.5.3'


But i cant connect to the webgui, any idea?

**Comment by szemere** [comment]
Hello @eihns,
 could you please share the exact commands you executed? Please also share the hash of your image, so we can be sure which version do you have.

Br,
Laci

**Comment by CurlyFlow** [comment]
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='splunk' --net='br0' --ip='192.168.86.166' --log-opt max-size='10m' --log-opt max-file='3' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'TCP_PORT_8000'='8000' -e 'TCP_PORT_8089'='8089' -e 'TCP_PORT_9997'='9997' -e 'UDP_PORT_514'='514' -e 'TCP_PORT_8088'='8088' -v '/mnt/user/appdata/splunk/var':'/opt/splunk/var':'rw' -v '/mnt/user/appdata/splunk/etc':'/opt/splunk/etc':'rw' -v '/var/log':'/data':'ro' -v '/var/lib/docker':'/dockervarlib':'ro' 'zyphermonkey/splunk' 


Dont know how to hash it.

Or is it that? 98992c7be78e50a103afd612ce3c5e6f1f52e9295897ad43c8e19fd02a149f78

**Comment by CurlyFlow** [comment]
have connected to the container and run

root@98992c7be78e:/# sudo netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.11:36425        0.0.0.0:*               LISTEN      -         

So its not startet...?!

Couldnt find anything related to syslog on *log in /var/logs either...

**Comment by szemere** [comment]
Hello @eihns,
 I try to split it into threads:

- Yes, the hash is right. (i.e. it is printed by the `docker images` command in the "Image ID" column)

- You are trying to run the `zyphermonkey/splunk` docker image, which is based on the `phusion/baseimage`. (None of them maintained by us.)
Containing an outdated version of syslog-ng (3.5.3), I did not find any config modification, but be aware that the newest options of syslog-ng will not work.

- Actually there is no syslog-ng error message on the copied output
`Nov 15 08:35:54 a688b24c81ac syslog-ng[13]: syslog-ng starting up; version='3.5.3'`
This line indicates that syslog-ng has started successfully.

- The webui is not a syslog-ng service, so the problem must be somewhere else.

**Comment by CurlyFlow** [comment]
Sorry, i mconfused. The docker linked to this here.

Anyway, im installing now your docker. Sorry for the confusion.

**Comment by mitzkia** [comment]
For now I am closing this issue. 
If you have any trouble with balabit/syslog-ng image we were willingly help you in that.
