### ISSUE TITLE
[Feature] Raspberry Pi / ARM Support

### ISSUE THREAD

**Issue by drexlma** [balabit/syslog-ng-docker#54]
Is this possible?

**Comment by MrAnno** [comment]
syslog-ng runs on ARM, we have unofficial packages for Raspbian 9 and 10:
https://download.opensuse.org/repositories/home:/laszlo_budai:/syslog-ng/Raspbian_10/

So yeah, I think it's possible to do the same in Docker. :)

**Comment by NickJLange** [comment]
So having just gone through the exercise this morning:

- by default, podman selects the wrong architecture "podman pull balabit/syslog-ng:latest"

` "standard_init_linux.go:219: exec user process caused: exec format error"`

- a manual pull of stretch / image-generation works just fine - no changes required

I've seen an ARCH statement before in other dockerfiles, so if I get some time I'll experiment with adding an explicit flag.. although I have no clear idea of how to get that as a selectable option on the main docker repo.

**Comment by gitneko** [comment]
Unfortunately on Raspberry Pi 4 8G with Ubuntu 20.04 (arm64) it's not so easy as just manually pulling and building the image.

Building the image fails at `RUN apt-get update -qq && apt-get install -y libdbd-mysql libdbd-pgsql libdbd-sqlite3 syslog-ng` with
```
The following packages have unmet dependencies:
 syslog-ng : Depends: syslog-ng-core (>= 3.30.1) but 3.8.1-10 is to be installed
             Recommends: syslog-ng-mod-smtp but it is not going to be installed
             Recommends: syslog-ng-mod-amqp but it is not going to be installed
             Recommends: syslog-ng-mod-geoip2 but it is not installable
             Recommends: syslog-ng-mod-redis but it is not going to be installed
             Recommends: syslog-ng-mod-stomp but it is not going to be installed
             Recommends: syslog-ng-mod-riemann but it is not going to be installed
             Recommends: syslog-ng-mod-graphite but it is not going to be installed
             Recommends: syslog-ng-mod-python but it is not going to be installed
             Recommends: syslog-ng-mod-add-contextual-data but it is not going to be installed
             Recommends: syslog-ng-mod-getent but it is not installable
             Recommends: syslog-ng-mod-stardate but it is not installable
             Recommends: syslog-ng-mod-map-value-pairs but it is not installable
             Recommends: syslog-ng-mod-snmp but it is not installable
             Recommends: syslog-ng-mod-xml-parser but it is not installable
             Recommends: syslog-ng-mod-http but it is not installable
             Recommends: syslog-ng-mod-rdkafka but it is not installable
             Recommends: syslog-ng-mod-examples but it is not installable
             Recommends: syslog-ng-mod-slog but it is not installable
             Recommends: syslog-ng-mod-java but it is not installable
             Recommends: syslog-ng-mod-java-common-lib but it is not installable
             Recommends: syslog-ng-mod-elastic but it is not installable
             Recommends: syslog-ng-mod-hdfs but it is not installable
             Recommends: syslog-ng-mod-kafka but it is not going to be installed
             Recommends: syslog-ng-mod-java-http but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by NickJLange** [comment]
As this is a Debian upstream - I'm going to guess some awareness is required for the apt-calls (Debian maxes out at 3.28...). I did put in a Pull-Request to start to address a fix..

[Pull-Request](https://github.com/balabit/syslog-ng-docker/pull/69)

**Comment by MrAnno** [comment]
Closing, as we are about to archive this repository.
https://github.com/balabit/syslog-ng-docker#deprecation-warning

Please open a new enhancement request in the [syslog-ng/syslog-ng](https://github.com/syslog-ng/syslog-ng/) repository, if you are still interested in this topic.
