### ISSUE TITLE
Error response when trying to run 

### ISSUE THREAD

**Issue by narang-amit** [balabit/syslog-ng-docker#57]
I recently downloaded Docker on my Mac and tried to use the syslog-ng Docker. After running `docker pull balabit/syslog-ng` successfully, I tried running `sudo docker run -it -p 514:514/udp -p 601:601 --name syslog-ng balabit/syslog-ng:latest` and repeatedly kept getting the following error:

`[2020-06-26T16:39:55.200875] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.27 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file; config-version='3.18'
[2020-06-26T16:39:55.292159] You have a TLS enabled source without a X.509 keypair. Make sure you have tls(key-file() and cert-file()) options, TLS handshake to this source will fail; location='/etc/syslog-ng/syslog-ng.conf:21:2'` 

Someone else tried replicating the steps and got the same error. I think there might be something wrong.

**Comment by Kokan** [comment]
These are not errors, rather warnings and running syslog-ng you should be able to.
The first one is only a version mismatch, in this case syslog-ng is going to run in compatible mode, it is not critical but the point that version should be updated in this repository is valid.
The second warning is regarding the tls connection, the default configuration for the docker uses a `default-network-drivers`, that tries to listen multiple source, from which one of them is using TLS. But we cannot supply key, cert files as we don't have them. As a result it warns that if you want to use those source with TLS, you must provides those files, if you don't want to you could simply ignore that warning.

**Comment by gaborznagy** [comment]
Hi @narang-amit. I'm closing this ticket due to inactivity.

I've bumped the version of the default config in the repository: https://github.com/balabit/syslog-ng-docker/pull/59

If you have any question, or issue, feel free to comment here and we will reopen the ticket.
