### ISSUE TITLE
Question, what does the -edv at the very end of the docker run command do ?

### ISSUE THREAD

**Issue by bvanbens** [balabit/syslog-ng-docker#58]
Wondering what those arguments do.
Thanks
sudo docker run -it -p 514:514/udp -p 601:601 --name syslog-ng balabit/syslog-ng:latest -edv  <--- what does (-edv) mean ?

**Comment by Kokan** [comment]
The arguments after a docker image are passed to the executable as arguments specified in ENTRYPOINT in the Dockerfile. In this case it is a `/usr/sbin/syslog-ng` instance; the flags in question can be looked up in syslsog-ng documentation (or simply use --help after docker image).

* e: means redirect internal logs to the stderr
* d: means turn on debug logs
* v: means turn on verbose logs

**Comment by gaborznagy** [comment]
As the question is answered, I'm closing this ticket.
If you still have questions, feel free to post a comment, and we reopen it.
