### ISSUE TITLE
mod-java load problem

### ISSUE THREAD

**Issue by czanik** [balabit/syslog-ng-docker#6]
When starting syslog-ng in docker, I receive the following error message:
"
Error opening plugin module; module='mod-java', error='libjvm.so:
cannot open shared object file: No such file or directory'
"
This can be worked around by adding the path to libjvm.so to /etc/ld.so.conf

**Comment by mitzkia** [comment]
Thanks for the report, i will fix it soon.

**Comment by mitzkia** [comment]
Pull request is created: #8

**Comment by mitzkia** [comment]
@czanik  Could you try it with the latest version?

**Comment by mitzkia** [comment]
Discussed with @czanik we can close this issue.
