### ISSUE TITLE
'No such file or directory' When using variables in the destination path.

### ISSUE THREAD

**Issue by RaceAap** [balabit/syslog-ng-docker#60]
I get the error:  syslog-ng[1]: Error opening file for writing; filename='/var/log/syslog/server01/2020/09/user', error='No such file or directory (2)'

This is the effected config part: 

destination hosts { 
    file("/var/log/syslog/$HOST/$YEAR/$MONTH/$FACILITY-$DAY");
};

I'm running the latest syslog-ng docker image on a Synology ds920+ with Docker.

**Comment by szemere** [comment]
Hello @RaceAap,
 If you would like to create directories with templates add `create-dirs(yes)` to your configuration.

 It is turned off by default for security reasons. (Syslog-ng tries to sanitize the file path, but it is more secure to not create any directories on the system based on potentially harmful inputs.)

Br,
Laci

**Comment by RaceAap** [comment]
Thanks Laci, that did the trick.
it was an user error ;-)
