### ISSUE TITLE
Default log filename?

### ISSUE THREAD

**Issue by zchef2k** [balabit/syslog-ng-docker#61]
Is there a trick with getting the default log to name itself other than the ID of the container? I've successfully set the ```--hostname``` of the container but syslog-ng still writes its own log out as ```<container id>.log```.

**Comment by szemere** [comment]
Hello @zchef2k,
 the default config (shipped with the container) logs to `/var/log/messages` , so I assume something overrides it. Can you share some details about your setup?

Br,
Laci

**Comment by gaborznagy** [comment]
I'm closing this ticket due to inactivity.
@zchef2k feel free to comment on this issue and we can reopen it.
