### ISSUE TITLE
Unable to initialize database access (DBI); rc=’-1′, error=’No such file or directory (2)’

### ISSUE THREAD

**Issue by si458** [balabit/syslog-ng-docker#62]
**Unable to initialize database access (DBI); rc=’-1′, error=’No such file or directory (2)’**
i am unable to use the `sql()` to insert records into a mysql database
it appears the `libdbd-mysql` package is missing 
can this be included?

**Comment by gaborznagy** [comment]
Hi, sorry for the late reply!

Yes, libdbi drivers should be installed as well. 
Thanks for reporting, I've opened a PR for that!

**Comment by si458** [comment]
Brilliant thank you!

That will help with stuff
