### ISSUE TITLE
Add builder script to the builder env image

### ISSUE THREAD

**Issue by lbudai** [balabit/syslog-ng-docker#7]
checkout_and_build_syslog_ng.sh should be included within the image

**Comment by mitzkia** [comment]
It is already included in every image, as we git clone the self github project in every basic-build-environments images.
This file is placed in "/syslog-ng-docker/shared-resources/build-scripts/" directory inside every image.
I use this "git clone" way because i think it is not a good way to maintain same script per image.

**Comment by lbudai** [comment]
I see... 
I wouldn't checkout syslog-ng-docker git repo: 
- users don't want to modify it (these images are not for maintaining those scripts)
- little bit confusing and overcomplicated from users point of view

**Comment by mitzkia** [comment]
Ok. But I don't understand what would be the advantage to put separately "checkout_and_build_syslog_ng.sh" script into every image. I can imagine only transparency as advantage. But in this case transparency plays versus maintainability.
As I correctly understand you, your idea is something like this? Am I right?
(display is not correct, thank you GitHub Markdown, there is checkout_and_build_syslog_ng_incubator.sh, checkout_and_build_syslog_ng.sh and Dockerfile inside directory 3.6 and 3.7)

├── developement-images
│   ├── centos_7
│   │   ├── 3.6
│   │   │   ├── checkout_and_build_syslog_ng_incubator.sh
│   │   │   ├── checkout_and_build_syslog_ng.sh
│   │   │   └── Dockerfile
│   │   └── 3.7
│   │         ├── checkout_and_build_syslog_ng_incubator.sh
│   │         ├── checkout_and_build_syslog_ng.sh
│   │         └── Dockerfile
│   ├── debian_jessie
│   │   ├── 3.6
│   │   │   ├── checkout_and_build_syslog_ng_incubator.sh
│   │   │   ├── checkout_and_build_syslog_ng.sh
│   │   │   └── Dockerfile
│   │   └── 3.7
│   │         ├── checkout_and_build_syslog_ng_incubator.sh
│   │         ├── checkout_and_build_syslog_ng.sh
│   │         └── Dockerfile
│   └── ubuntu_trusty
│       ├── 3.6
│       │   ├── checkout_and_build_syslog_ng_incubator.sh
│       │   ├── checkout_and_build_syslog_ng.sh
│       │   └── Dockerfile
│       └── 3.7
│             ├── checkout_and_build_syslog_ng_incubator.sh
│             ├── checkout_and_build_syslog_ng.sh
│             └── Dockerfile

**Comment by mitzkia** [comment]
Sorry, I just rereading the title of the issue. :)
You mean to put scripts into the "basic-build-environment" images, not to "developement-images". If this so, I can take up with the idea of it.

**Comment by mitzkia** [comment]
Created a pull request: #8

**Comment by mitzkia** [comment]
@lbudai I think we can close this issue. The structure is totally different for now.
