### ISSUE TITLE
Change log file name to container name

### ISSUE THREAD

**Issue by hassanakhtar** [balabit/syslog-ng-docker#72]
I have a scenario and created a syslog container using this syslog-ng repository and I am redirecting my other container logs to this logging container, I used the file naming pattern to be: ` file("/var/log/messages_${PROGRAM}-${YEAR}${MONTH}${DAY}");`. I tried different macros/variables in this file naming pattern but I couldn't get that. `${PROGRAM}` returns the container ID. Is there any way to get container name instead of ID?

**Comment by Kokan** [comment]
syslog-ng itself are not able to retrive a container name for a container id. if you are using docker, this option to configure should help: https://docs.docker.com/config/containers/logging/log_tags/. disclaimer, I haven't tried this out.

**Comment by hassanakhtar** [comment]
Thanks a lot @Kokan. I added `--log-opt tag="{{.Name}}"` to run the containers sending logs. So now the ${PROGRAM} is yielding the container name instead of the Container ID. 👍
