### ISSUE TITLE
Suppport for TLSv1.3

### ISSUE THREAD

**Issue by matt1003** [balabit/syslog-ng-docker#74]
Currently the syslog-ng-docker container is using openSSL version 1.1.0l, however support for TLSv1.3 was only introduced in openSSL version 1.1.1. 

```
docker run --rm -it --entrypoint /bin/sh  balabit/syslog-ng       
# openssl version
OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by matt1003** [comment]
Note: Debian 9 (stretch) uses openSSL 1.1.0l-1, whereas Debian 10 (buster) uses openSSL 1.1.1d-0.

**Comment by gaborznagy** [comment]
Hi @matt1003 ! Thanks for opening a request!

I've created a PR to upgrade the base image of `balabit/syslog-ng`, see #75
